# Generated by Django 3.0.2 on 2020-01-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccounts',
            new_name='UserAccount',
        ),
    ]
