# Generated by Django 3.0.2 on 2020-01-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200117_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='img',
            new_name='file_user',
        ),
    ]
